import { storage } from "./storage";
import { InsertBrand } from "@shared/schema";

// Sample sunglass brand data for investor analysis
const sampleBrands: InsertBrand[] = [
  {
    name: "Ray-Ban",
    category: "luxury",
    revenue: "3200000000",
    growthRate: "8.5",
    marketShare: "15.2",
    investmentScore: 85,
    founded: 1937,
    employees: 8500,
    website: "https://ray-ban.com",
    description: "Iconic eyewear brand known for Aviator and Wayfarer styles, owned by EssilorLuxottica",
    isPublic: true,
    locations: ["USA", "Italy", "Global"]
  },
  {
    name: "Oakley",
    category: "sports",
    revenue: "2800000000",
    growthRate: "12.3",
    marketShare: "12.8",
    investmentScore: 88,
    founded: 1975,
    employees: 6200,
    website: "https://oakley.com",
    description: "Performance sports sunglasses with cutting-edge technology and military contracts",
    isPublic: true,
    locations: ["USA", "Asia", "Europe"]
  },
  {
    name: "Warby Parker",
    category: "d2c",
    revenue: "540000000",
    growthRate: "24.7",
    marketShare: "2.1",
    investmentScore: 92,
    founded: 2010,
    employees: 3500,
    website: "https://warbyparker.com",
    description: "D2C eyewear disruptor with strong online presence and growing retail footprint",
    isPublic: true,
    locations: ["USA", "Canada"]
  },
  {
    name: "Maui Jim",
    category: "premium",
    revenue: "350000000",
    growthRate: "15.8",
    marketShare: "3.2",
    investmentScore: 78,
    founded: 1980,
    employees: 1200,
    website: "https://mauijim.com",
    description: "Premium polarized sunglasses brand with strong presence in outdoor and marine markets",
    isPublic: false,
    locations: ["USA", "Hawaii", "International"]
  },
  {
    name: "Persol",
    category: "luxury",
    revenue: "180000000",
    growthRate: "6.2",
    marketShare: "1.8",
    investmentScore: 72,
    founded: 1917,
    employees: 450,
    website: "https://persol.com",
    description: "Italian luxury eyewear with handcrafted frames and celebrity endorsements",
    isPublic: true,
    locations: ["Italy", "Europe", "USA"]
  },
  {
    name: "Costa Del Mar",
    category: "sports",
    revenue: "220000000",
    growthRate: "18.5",
    marketShare: "2.8",
    investmentScore: 81,
    founded: 1983,
    employees: 800,
    website: "https://costadelmar.com",
    description: "Fishing and marine sports sunglasses with polarized lens technology",
    isPublic: false,
    locations: ["USA", "Coastal Markets"]
  },
  {
    name: "Gentle Monster",
    category: "luxury",
    revenue: "320000000",
    growthRate: "45.2",
    marketShare: "1.5",
    investmentScore: 94,
    founded: 2011,
    employees: 1800,
    website: "https://gentlemonster.com",
    description: "Korean luxury eyewear brand with avant-garde designs and strong Asian market presence",
    isPublic: false,
    locations: ["South Korea", "Asia", "USA", "Europe"]
  },
  {
    name: "Luxottica Store Brands",
    category: "mass-market",
    revenue: "4200000000",
    growthRate: "4.8",
    marketShare: "18.7",
    investmentScore: 76,
    founded: 1961,
    employees: 82000,
    website: "https://luxottica.com",
    description: "Largest eyewear conglomerate with multiple brand portfolio and retail presence",
    isPublic: true,
    locations: ["Italy", "Global"]
  },
  {
    name: "Roka",
    category: "sports",
    revenue: "45000000",
    growthRate: "67.3",
    marketShare: "0.3",
    investmentScore: 89,
    founded: 2013,
    employees: 150,
    website: "https://roka.com",
    description: "High-performance sports eyewear for cycling, running, and triathlon athletes",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Goodr",
    category: "d2c",
    revenue: "25000000",
    growthRate: "89.4",
    marketShare: "0.2",
    investmentScore: 85,
    founded: 2015,
    employees: 75,
    website: "https://goodr.com",
    description: "Affordable, fun running sunglasses with viral marketing and strong social media presence",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Safilo Group",
    category: "premium",
    revenue: "980000000",
    growthRate: "3.2",
    marketShare: "5.8",
    investmentScore: 68,
    founded: 1934,
    employees: 8900,
    website: "https://safilo.com",
    description: "Italian eyewear manufacturer with licensed brands and global distribution",
    isPublic: true,
    locations: ["Italy", "Global"]
  },
  {
    name: "Bolle",
    category: "sports",
    revenue: "65000000",
    growthRate: "8.9",
    marketShare: "0.7",
    investmentScore: 71,
    founded: 1888,
    employees: 280,
    website: "https://bolle.com",
    description: "French sports eyewear brand specializing in skiing and cycling protection",
    isPublic: false,
    locations: ["France", "Europe", "USA"]
  },
  {
    name: "Zenni Optical",
    category: "d2c",
    revenue: "380000000",
    growthRate: "28.7",
    marketShare: "1.9",
    investmentScore: 86,
    founded: 2003,
    employees: 2200,
    website: "https://zenni.com",
    description: "Online-first affordable eyewear with customization options and virtual try-on",
    isPublic: false,
    locations: ["USA", "Online Global"]
  },
  {
    name: "Randolph Engineering",
    category: "premium",
    revenue: "18000000",
    growthRate: "12.1",
    marketShare: "0.15",
    investmentScore: 73,
    founded: 1973,
    employees: 95,
    website: "https://randolphusa.com",
    description: "American-made military and aviation sunglasses with government contracts",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Spy Optic",
    category: "sports",
    revenue: "42000000",
    growthRate: "5.4",
    marketShare: "0.4",
    investmentScore: 65,
    founded: 1994,
    employees: 120,
    website: "https://spyoptic.com",
    description: "Action sports eyewear with focus on snow sports and youth market",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Coco and Breezy",
    category: "luxury",
    revenue: "8000000",
    growthRate: "34.5",
    marketShare: "0.05",
    investmentScore: 79,
    founded: 2009,
    employees: 25,
    website: "https://cocoandbreezy.com",
    description: "Celebrity-endorsed luxury eyewear with unique designs and limited editions",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Shwood",
    category: "sustainable",
    revenue: "12000000",
    growthRate: "22.8",
    marketShare: "0.08",
    investmentScore: 77,
    founded: 2009,
    employees: 55,
    website: "https://shwoodshop.com",
    description: "Sustainable wooden sunglasses with eco-friendly materials and artisan craftsmanship",
    isPublic: false,
    locations: ["USA", "Portland"]
  },
  {
    name: "Blenders Eyewear",
    category: "d2c",
    revenue: "35000000",
    growthRate: "76.2",
    marketShare: "0.25",
    investmentScore: 88,
    founded: 2012,
    employees: 85,
    website: "https://blenderseyewear.com",
    description: "Lifestyle sunglasses brand with strong social media presence and festival marketing",
    isPublic: false,
    locations: ["USA", "California"]
  },
  {
    name: "Native Eyewear",
    category: "sports",
    revenue: "28000000",
    growthRate: "9.7",
    marketShare: "0.22",
    investmentScore: 69,
    founded: 2001,
    employees: 65,
    website: "https://nativeyewear.com",
    description: "Outdoor sports eyewear with focus on fishing, skiing, and mountain activities",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Wiley X",
    category: "sports",
    revenue: "85000000",
    growthRate: "14.3",
    marketShare: "0.6",
    investmentScore: 75,
    founded: 1987,
    employees: 320,
    website: "https://wileyx.com",
    description: "Protective eyewear for military, law enforcement, and extreme sports",
    isPublic: false,
    locations: ["USA", "International"]
  },
  // Luxury Premium Brands
  {
    name: "Tom Ford",
    category: "luxury",
    revenue: "450000000",
    growthRate: "11.2",
    marketShare: "2.8",
    investmentScore: 83,
    founded: 2005,
    employees: 1200,
    website: "https://tomford.com",
    description: "High-end fashion eyewear with celebrity following and luxury retail presence",
    isPublic: false,
    locations: ["USA", "Europe", "Asia"]
  },
  {
    name: "Gucci",
    category: "luxury",
    revenue: "380000000",
    growthRate: "8.7",
    marketShare: "2.1",
    investmentScore: 81,
    founded: 1921,
    employees: 950,
    website: "https://gucci.com",
    description: "Italian luxury fashion house with premium eyewear collection",
    isPublic: true,
    locations: ["Italy", "Global"]
  },
  {
    name: "Prada",
    category: "luxury",
    revenue: "290000000",
    growthRate: "6.4",
    marketShare: "1.7",
    investmentScore: 78,
    founded: 1913,
    employees: 820,
    website: "https://prada.com",
    description: "Italian luxury brand with innovative eyewear designs and premium materials",
    isPublic: true,
    locations: ["Italy", "Global"]
  },
  {
    name: "Dior",
    category: "luxury",
    revenue: "420000000",
    growthRate: "9.8",
    marketShare: "2.4",
    investmentScore: 85,
    founded: 1946,
    employees: 1100,
    website: "https://dior.com",
    description: "French luxury fashion house with haute couture eyewear collections",
    isPublic: true,
    locations: ["France", "Global"]
  },
  {
    name: "Versace",
    category: "luxury",
    revenue: "165000000",
    growthRate: "12.5",
    marketShare: "0.9",
    investmentScore: 76,
    founded: 1978,
    employees: 480,
    website: "https://versace.com",
    description: "Italian luxury brand known for bold designs and Medusa logo eyewear",
    isPublic: false,
    locations: ["Italy", "Global"]
  },
  {
    name: "Chanel",
    category: "luxury",
    revenue: "310000000",
    growthRate: "7.2",
    marketShare: "1.8",
    investmentScore: 82,
    founded: 1910,
    employees: 750,
    website: "https://chanel.com",
    description: "French luxury fashion house with timeless and elegant eyewear designs",
    isPublic: false,
    locations: ["France", "Global"]
  },
  {
    name: "Dolce & Gabbana",
    category: "luxury",
    revenue: "195000000",
    growthRate: "8.9",
    marketShare: "1.1",
    investmentScore: 74,
    founded: 1985,
    employees: 580,
    website: "https://dolcegabbana.com",
    description: "Italian luxury brand with Sicilian-inspired bold eyewear designs",
    isPublic: false,
    locations: ["Italy", "Global"]
  },
  {
    name: "Burberry",
    category: "luxury",
    revenue: "145000000",
    growthRate: "5.8",
    marketShare: "0.8",
    investmentScore: 71,
    founded: 1856,
    employees: 420,
    website: "https://burberry.com",
    description: "British luxury brand with heritage trench coat inspired eyewear",
    isPublic: true,
    locations: ["UK", "Global"]
  },
  {
    name: "Saint Laurent",
    category: "luxury",
    revenue: "225000000",
    growthRate: "13.4",
    marketShare: "1.3",
    investmentScore: 79,
    founded: 1961,
    employees: 640,
    website: "https://ysl.com",
    description: "French luxury brand with rock-and-roll inspired eyewear aesthetic",
    isPublic: true,
    locations: ["France", "Global"]
  },
  {
    name: "Cartier",
    category: "luxury",
    revenue: "185000000",
    growthRate: "9.1",
    marketShare: "1.0",
    investmentScore: 80,
    founded: 1847,
    employees: 520,
    website: "https://cartier.com",
    description: "French luxury jeweler with premium eyewear featuring precious materials",
    isPublic: true,
    locations: ["France", "Global"]
  },
  // Sports Performance Brands
  {
    name: "Adidas Eyewear",
    category: "sports",
    revenue: "125000000",
    growthRate: "16.7",
    marketShare: "0.7",
    investmentScore: 77,
    founded: 1949,
    employees: 380,
    website: "https://adidas.com",
    description: "German sports brand with performance eyewear for various athletic activities",
    isPublic: true,
    locations: ["Germany", "Global"]
  },
  {
    name: "Nike Vision",
    category: "sports",
    revenue: "98000000",
    growthRate: "19.3",
    marketShare: "0.6",
    investmentScore: 78,
    founded: 1971,
    employees: 290,
    website: "https://nike.com",
    description: "American sports giant with performance-focused eyewear technology",
    isPublic: true,
    locations: ["USA", "Global"]
  },
  {
    name: "Under Armour Eyewear",
    category: "sports",
    revenue: "54000000",
    growthRate: "22.8",
    marketShare: "0.3",
    investmentScore: 73,
    founded: 1996,
    employees: 165,
    website: "https://underarmour.com",
    description: "American athletic brand with moisture-wicking and performance eyewear",
    isPublic: true,
    locations: ["USA", "Global"]
  },
  {
    name: "Uvex",
    category: "sports",
    revenue: "89000000",
    growthRate: "8.4",
    marketShare: "0.5",
    investmentScore: 72,
    founded: 1926,
    employees: 320,
    website: "https://uvex.com",
    description: "German safety and sports eyewear with industrial and athletic applications",
    isPublic: false,
    locations: ["Germany", "Europe", "USA"]
  },
  {
    name: "Julbo",
    category: "sports",
    revenue: "35000000",
    growthRate: "14.1",
    marketShare: "0.2",
    investmentScore: 74,
    founded: 1888,
    employees: 125,
    website: "https://julbo.com",
    description: "French mountain and glacier eyewear specialist with extreme condition protection",
    isPublic: false,
    locations: ["France", "Europe", "USA"]
  },
  {
    name: "Smith Optics",
    category: "sports",
    revenue: "78000000",
    growthRate: "11.8",
    marketShare: "0.45",
    investmentScore: 76,
    founded: 1965,
    employees: 280,
    website: "https://smithoptics.com",
    description: "American snow sports and cycling eyewear with ChromaPop lens technology",
    isPublic: false,
    locations: ["USA", "Global"]
  },
  {
    name: "Alpina Sports",
    category: "sports",
    revenue: "42000000",
    growthRate: "9.6",
    marketShare: "0.25",
    investmentScore: 69,
    founded: 1980,
    employees: 155,
    website: "https://alpina-sports.com",
    description: "German cycling and winter sports eyewear with innovative lens technology",
    isPublic: false,
    locations: ["Germany", "Europe"]
  },
  {
    name: "Rudy Project",
    category: "sports",
    revenue: "48000000",
    growthRate: "13.2",
    marketShare: "0.28",
    investmentScore: 75,
    founded: 1985,
    employees: 180,
    website: "https://rudyproject.com",
    description: "Italian cycling and triathlon eyewear with aerodynamic designs",
    isPublic: false,
    locations: ["Italy", "Global"]
  },
  {
    name: "100% Eyewear",
    category: "sports",
    revenue: "32000000",
    growthRate: "27.4",
    marketShare: "0.18",
    investmentScore: 79,
    founded: 1982,
    employees: 95,
    website: "https://100percent.com",
    description: "American motocross and cycling eyewear with retro-inspired designs",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Tifosi Optics",
    category: "sports",
    revenue: "18000000",
    growthRate: "21.7",
    marketShare: "0.1",
    investmentScore: 72,
    founded: 2003,
    employees: 45,
    website: "https://tifosioptics.com",
    description: "Affordable performance cycling and running eyewear with Italian-inspired designs",
    isPublic: false,
    locations: ["USA"]
  },
  // Direct-to-Consumer Innovators
  {
    name: "Felix Gray",
    category: "d2c",
    revenue: "67000000",
    growthRate: "42.8",
    marketShare: "0.4",
    investmentScore: 84,
    founded: 2016,
    employees: 185,
    website: "https://felixgray.com",
    description: "Blue light blocking and computer eyewear for digital professionals",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "EyeBuyDirect",
    category: "d2c",
    revenue: "185000000",
    growthRate: "31.5",
    marketShare: "1.1",
    investmentScore: 82,
    founded: 2006,
    employees: 520,
    website: "https://eyebuydirect.com",
    description: "Online affordable eyewear with virtual try-on and prescription options",
    isPublic: false,
    locations: ["USA", "Global"]
  },
  {
    name: "Firmoo",
    category: "d2c",
    revenue: "95000000",
    growthRate: "38.2",
    marketShare: "0.55",
    investmentScore: 76,
    founded: 2009,
    employees: 285,
    website: "https://firmoo.com",
    description: "Global online eyewear retailer with fashion-forward designs and affordable pricing",
    isPublic: false,
    locations: ["China", "USA", "Global"]
  },
  {
    name: "Coastal",
    category: "d2c",
    revenue: "142000000",
    growthRate: "18.9",
    marketShare: "0.8",
    investmentScore: 73,
    founded: 2000,
    employees: 425,
    website: "https://coastal.com",
    description: "Canadian online eyewear retailer with prescription and sunglasses options",
    isPublic: false,
    locations: ["Canada", "USA"]
  },
  {
    name: "Lensabl",
    category: "d2c",
    revenue: "28000000",
    growthRate: "67.8",
    marketShare: "0.16",
    investmentScore: 85,
    founded: 2017,
    employees: 85,
    website: "https://lensabl.com",
    description: "Prescription lens replacement service for existing sunglasses and frames",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Glasses.com",
    category: "d2c",
    revenue: "78000000",
    growthRate: "25.4",
    marketShare: "0.45",
    investmentScore: 74,
    founded: 2009,
    employees: 235,
    website: "https://glasses.com",
    description: "Online eyewear with home try-on program and prescription services",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Liingo Eyewear",
    category: "d2c",
    revenue: "22000000",
    growthRate: "56.3",
    marketShare: "0.13",
    investmentScore: 79,
    founded: 2016,
    employees: 65,
    website: "https://liingoeyewear.com",
    description: "Affordable designer eyewear with home try-on and quick delivery",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Diff Eyewear",
    category: "d2c",
    revenue: "45000000",
    growthRate: "78.9",
    marketShare: "0.26",
    investmentScore: 88,
    founded: 2015,
    employees: 125,
    website: "https://diffeyewear.com",
    description: "Celebrity-endorsed sunglasses with charitable giving and social media marketing",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Privé Revaux",
    category: "d2c",
    revenue: "72000000",
    growthRate: "145.7",
    marketShare: "0.42",
    investmentScore: 91,
    founded: 2017,
    employees: 195,
    website: "https://priverevaux.com",
    description: "Celebrity co-founded affordable luxury sunglasses with strong social media presence",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Quay Australia",
    category: "d2c",
    revenue: "98000000",
    growthRate: "34.6",
    marketShare: "0.56",
    investmentScore: 83,
    founded: 2004,
    employees: 285,
    website: "https://quayaustralia.com",
    description: "Australian festival and influencer-inspired sunglasses with global reach",
    isPublic: false,
    locations: ["Australia", "USA", "Global"]
  },
  // Sustainable and Eco-Friendly Brands
  {
    name: "Pela Vision",
    category: "sustainable",
    revenue: "15000000",
    growthRate: "89.4",
    marketShare: "0.09",
    investmentScore: 82,
    founded: 2019,
    employees: 45,
    website: "https://pela.earth",
    description: "Plant-based biodegradable sunglasses made from flax straw waste",
    isPublic: false,
    locations: ["Canada", "USA"]
  },
  {
    name: "Proof Eyewear",
    category: "sustainable",
    revenue: "8000000",
    growthRate: "34.2",
    marketShare: "0.05",
    investmentScore: 76,
    founded: 2010,
    employees: 25,
    website: "https://proofeyewear.com",
    description: "Wooden and sustainable material eyewear with artisan craftsmanship",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Revo",
    category: "sustainable",
    revenue: "52000000",
    growthRate: "12.8",
    marketShare: "0.3",
    investmentScore: 73,
    founded: 1985,
    employees: 185,
    website: "https://revo.com",
    description: "Ocean plastic and recycled material sunglasses with polarized lenses",
    isPublic: false,
    locations: ["USA", "Global"]
  },
  {
    name: "Sea2see",
    category: "sustainable",
    revenue: "6000000",
    growthRate: "67.5",
    marketShare: "0.035",
    investmentScore: 78,
    founded: 2016,
    employees: 18,
    website: "https://sea2see.org",
    description: "Eyewear made from marine plastic waste collected by fishing communities",
    isPublic: false,
    locations: ["Spain", "Europe"]
  },
  {
    name: "WOODone",
    category: "sustainable",
    revenue: "3500000",
    growthRate: "45.8",
    marketShare: "0.02",
    investmentScore: 74,
    founded: 2018,
    employees: 12,
    website: "https://woodone.co",
    description: "Wooden sunglasses with sustainable forestry and carbon-neutral shipping",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "SOLO Eyewear",
    category: "sustainable",
    revenue: "9000000",
    growthRate: "28.7",
    marketShare: "0.05",
    investmentScore: 71,
    founded: 2012,
    employees: 32,
    website: "https://soloeyewear.com",
    description: "Bamboo and recycled plastic sunglasses with eyecare philanthropy",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Bamboa",
    category: "sustainable",
    revenue: "4200000",
    growthRate: "52.3",
    marketShare: "0.025",
    investmentScore: 75,
    founded: 2017,
    employees: 15,
    website: "https://bamboa.com",
    description: "Bamboo sunglasses with zero-waste packaging and tree planting program",
    isPublic: false,
    locations: ["Spain", "Europe"]
  },
  // Heritage and Classic Brands
  {
    name: "American Optical",
    category: "premium",
    revenue: "38000000",
    growthRate: "5.2",
    marketShare: "0.22",
    investmentScore: 68,
    founded: 1833,
    employees: 145,
    website: "https://aoeyewear.com",
    description: "Historic American eyewear brand with military and aviation heritage",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Oliver Peoples",
    category: "luxury",
    revenue: "85000000",
    growthRate: "7.8",
    marketShare: "0.5",
    investmentScore: 79,
    founded: 1987,
    employees: 285,
    website: "https://oliverpeoples.com",
    description: "California-based luxury eyewear with vintage-inspired designs",
    isPublic: true,
    locations: ["USA", "Global"]
  },
  {
    name: "Moscot",
    category: "premium",
    revenue: "45000000",
    growthRate: "11.4",
    marketShare: "0.26",
    investmentScore: 74,
    founded: 1915,
    employees: 165,
    website: "https://moscot.com",
    description: "Fifth-generation New York eyewear family business with iconic designs",
    isPublic: false,
    locations: ["USA", "International"]
  },
  {
    name: "Serengeti",
    category: "premium",
    revenue: "32000000",
    growthRate: "8.9",
    marketShare: "0.18",
    investmentScore: 71,
    founded: 1985,
    employees: 125,
    website: "https://serengeti-eyewear.com",
    description: "Photochromic and polarized lens technology for driving and outdoor activities",
    isPublic: false,
    locations: ["USA", "Italy"]
  },
  {
    name: "Vuarnet",
    category: "premium",
    revenue: "28000000",
    growthRate: "6.7",
    marketShare: "0.16",
    investmentScore: 69,
    founded: 1957,
    employees: 95,
    website: "https://vuarnet.com",
    description: "French alpine eyewear with mineral glass lenses and Olympic heritage",
    isPublic: false,
    locations: ["France", "Global"]
  },
  {
    name: "Carrera",
    category: "premium",
    revenue: "125000000",
    growthRate: "9.3",
    marketShare: "0.72",
    investmentScore: 76,
    founded: 1956,
    employees: 425,
    website: "https://carrera.com",
    description: "Austrian sports eyewear brand with racing heritage and celebrity endorsements",
    isPublic: true,
    locations: ["Austria", "Global"]
  },
  // Asian Market Leaders
  {
    name: "JINS",
    category: "mass-market",
    revenue: "485000000",
    growthRate: "15.8",
    marketShare: "2.8",
    investmentScore: 81,
    founded: 2001,
    employees: 3200,
    website: "https://jins.com",
    description: "Japanese eyewear retailer with affordable fashion frames and blue light protection",
    isPublic: true,
    locations: ["Japan", "Asia", "USA"]
  },
  {
    name: "Zoff",
    category: "mass-market",
    revenue: "320000000",
    growthRate: "12.4",
    marketShare: "1.8",
    investmentScore: 75,
    founded: 2005,
    employees: 2100,
    website: "https://zoff.co.jp",
    description: "Japanese affordable eyewear chain with quick service and fashion focus",
    isPublic: false,
    locations: ["Japan", "Asia"]
  },
  {
    name: "Owndays",
    category: "mass-market",
    revenue: "285000000",
    growthRate: "18.7",
    marketShare: "1.6",
    investmentScore: 78,
    founded: 2013,
    employees: 1850,
    website: "https://owndays.com",
    description: "Japanese eyewear retailer with same-day service and modern designs",
    isPublic: false,
    locations: ["Japan", "Asia", "Global"]
  },
  {
    name: "Formosa Optical",
    category: "premium",
    revenue: "198000000",
    growthRate: "8.9",
    marketShare: "1.1",
    investmentScore: 72,
    founded: 1957,
    employees: 1200,
    website: "https://formosa-optical.com",
    description: "Taiwanese eyewear manufacturer with precision optics and luxury frames",
    isPublic: true,
    locations: ["Taiwan", "Asia", "Global"]
  },
  {
    name: "Charmant",
    category: "premium",
    revenue: "165000000",
    growthRate: "6.8",
    marketShare: "0.95",
    investmentScore: 70,
    founded: 1956,
    employees: 980,
    website: "https://charmant.co.jp",
    description: "Japanese titanium eyewear specialist with lightweight and durable frames",
    isPublic: true,
    locations: ["Japan", "Global"]
  },
  // Emerging and Boutique Brands
  {
    name: "Akoni",
    category: "luxury",
    revenue: "42000000",
    growthRate: "68.4",
    marketShare: "0.24",
    investmentScore: 89,
    founded: 2019,
    employees: 125,
    website: "https://akoneyewear.com",
    description: "Luxury eyewear with Japanese craftsmanship and limited edition collections",
    isPublic: false,
    locations: ["Japan", "USA", "Europe"]
  },
  {
    name: "Thierry Lasry",
    category: "luxury",
    revenue: "18000000",
    growthRate: "24.6",
    marketShare: "0.1",
    investmentScore: 82,
    founded: 2006,
    employees: 55,
    website: "https://thierrylasry.com",
    description: "French luxury sunglasses with vintage-futuristic designs and handcrafted frames",
    isPublic: false,
    locations: ["France", "Global"]
  },
  {
    name: "Garrett Leight",
    category: "premium",
    revenue: "35000000",
    growthRate: "19.8",
    marketShare: "0.2",
    investmentScore: 84,
    founded: 2010,
    employees: 105,
    website: "https://garrettleight.com",
    description: "California-made eyewear with vintage inspiration and modern aesthetics",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "MYKITA",
    category: "luxury",
    revenue: "58000000",
    growthRate: "14.2",
    marketShare: "0.33",
    investmentScore: 86,
    founded: 2003,
    employees: 195,
    website: "https://mykita.com",
    description: "German innovative eyewear with 3D printing and architectural design approach",
    isPublic: false,
    locations: ["Germany", "Global"]
  },
  {
    name: "L.G.R",
    category: "luxury",
    revenue: "25000000",
    growthRate: "22.7",
    marketShare: "0.14",
    investmentScore: 80,
    founded: 2007,
    employees: 75,
    website: "https://lgr.it",
    description: "Italian luxury eyewear inspired by African safaris and vintage exploration",
    isPublic: false,
    locations: ["Italy", "Global"]
  },
  {
    name: "RETROSUPERFUTURE",
    category: "premium",
    revenue: "38000000",
    growthRate: "16.8",
    marketShare: "0.22",
    investmentScore: 77,
    founded: 2007,
    employees: 125,
    website: "https://retrosuperfuture.com",
    description: "Italian sunglasses combining retro aesthetics with modern materials",
    isPublic: false,
    locations: ["Italy", "Global"]
  },
  // Technology-Forward Brands
  {
    name: "Snapchat Spectacles",
    category: "tech",
    revenue: "45000000",
    growthRate: "134.8",
    marketShare: "0.26",
    investmentScore: 85,
    founded: 2016,
    employees: 185,
    website: "https://spectacles.com",
    description: "Smart sunglasses with camera and AR capabilities for social media content",
    isPublic: true,
    locations: ["USA"]
  },
  {
    name: "Ray-Ban Stories",
    category: "tech",
    revenue: "125000000",
    growthRate: "89.3",
    marketShare: "0.72",
    investmentScore: 88,
    founded: 2021,
    employees: 425,
    website: "https://ray-ban.com/stories",
    description: "Smart sunglasses collaboration between Ray-Ban and Meta with camera features",
    isPublic: true,
    locations: ["USA", "Global"]
  },
  {
    name: "Bose Frames",
    category: "tech",
    revenue: "78000000",
    growthRate: "67.2",
    marketShare: "0.45",
    investmentScore: 83,
    founded: 2019,
    employees: 285,
    website: "https://bose.com/frames",
    description: "Audio sunglasses with built-in speakers and voice assistant integration",
    isPublic: true,
    locations: ["USA", "Global"]
  },
  {
    name: "Lucyd",
    category: "tech",
    revenue: "12000000",
    growthRate: "156.7",
    marketShare: "0.07",
    investmentScore: 79,
    founded: 2017,
    employees: 45,
    website: "https://lucyd.co",
    description: "Bluetooth audio eyewear with prescription lens compatibility",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Vue Smart Glasses",
    category: "tech",
    revenue: "8000000",
    growthRate: "234.5",
    marketShare: "0.05",
    investmentScore: 81,
    founded: 2016,
    employees: 32,
    website: "https://vue.ai",
    description: "Smart glasses with gesture control and fitness tracking capabilities",
    isPublic: false,
    locations: ["USA"]
  },
  // Regional and Niche Brands
  {
    name: "Kaenon",
    category: "sports",
    revenue: "22000000",
    growthRate: "11.5",
    marketShare: "0.13",
    investmentScore: 72,
    founded: 2001,
    employees: 65,
    website: "https://kaenon.com",
    description: "California-based performance eyewear with polarized SR-91 lens technology",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Electric",
    category: "lifestyle",
    revenue: "35000000",
    growthRate: "8.7",
    marketShare: "0.2",
    investmentScore: 69,
    founded: 2000,
    employees: 125,
    website: "https://electriccalifornia.com",
    description: "California lifestyle brand with surf and snow sports inspired eyewear",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "VonZipper",
    category: "lifestyle",
    revenue: "28000000",
    growthRate: "6.9",
    marketShare: "0.16",
    investmentScore: 66,
    founded: 2000,
    employees: 95,
    website: "https://vonzipper.com",
    description: "Action sports lifestyle brand with bold designs and youth market focus",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Dragon Alliance",
    category: "sports",
    revenue: "42000000",
    growthRate: "9.8",
    marketShare: "0.24",
    investmentScore: 71,
    founded: 1993,
    employees: 155,
    website: "https://dragonalliance.com",
    description: "Snow sports and motocross eyewear with Lumalens color optimization",
    isPublic: false,
    locations: ["USA"]
  },
  {
    name: "Arnette",
    category: "lifestyle",
    revenue: "65000000",
    growthRate: "7.4",
    marketShare: "0.37",
    investmentScore: 68,
    founded: 1992,
    employees: 225,
    website: "https://arnette.com",
    description: "Action sports lifestyle brand with surf and skate culture influence",
    isPublic: true,
    locations: ["USA", "Global"]
  }
];

export async function seedDatabase() {
  console.log("Seeding database with sample brand data...");
  
  try {
    // Add all sample brands
    for (const brand of sampleBrands) {
      await storage.createBrand(brand);
    }
    
    // Update market metrics
    await storage.updateMarketMetrics({
      totalBrands: sampleBrands.length,
      marketSize: "28500000000", // $28.5B market size with expanded dataset
      opportunities: 47,
      insights: 0
    });
    
    console.log(`Successfully seeded ${sampleBrands.length} brands`);
    return { success: true, count: sampleBrands.length };
  } catch (error) {
    console.error("Error seeding database:", error);
    return { success: false, error: String(error) };
  }
}